[project]
name = "operacoes-numpy"
version = "0.1.0"
requires-python = ">= 3.8"
dependencies = [
    "numpy>=1.21.0"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"